# PyTorch Lesson 1

PyTorch is a deep learning framework developed by Facebook

Why PyTorch?
    - Extreme fast implementation of neural network
    - GPU support supporting fast implementation
    - 'Python' based language and made easy to understand/interepret
    - Support for all popular algorithms
    - Automatic differentiation available
    
    
## PyTorch ~ Numpy   

Lets now see how similar and easy to learn pytorch is to numpy

**1. How to create a tensor(any n-dimensional matrix)**

In [6]:
import torch
import numpy as np

In [32]:
#PyTorch
t_tensor = torch.tensor([[2,3,4],[3,2,1]])

#Numpy
n_array = np.array([[2,3,4],[3,2,1]])

print('-------PyTorch------\n\n',t_tensor,'\n')
print('-------Numpy--------\n\n',n_array,'\n')

-------PyTorch------

 tensor([[2, 3, 4],
        [3, 2, 1]]) 

-------Numpy--------

 [[2 3 4]
 [3 2 1]] 



**2.Querying the shape of the torch tensor is simlar to numpy way with the keyword** --->  *torch_tensor.shape*

In [33]:
#PyTorch
t_tensor = torch.tensor([[2,3,4],[3,2,1]])

#Numpy
n_array = np.array([[2,3,4],[3,2,1]])

print('-------PyTorch------\n\n',t_tensor.shape,'\n')
print('-------Numpy--------\n\n',n_array.shape,'\n')

-------PyTorch------

 torch.Size([2, 3]) 

-------Numpy--------

 (2, 3) 



**3.Random valued torch tensor can be created using** ---> *torch.rand(a, b) *

similar to the one in numpy as --->  np.random.rand(a, b)  where a & b are no.of rows and columns respectively

In [45]:
#PyTorch
t_tensor = torch.rand(2,2)

#Numpy
n_array = np.random.rand(2,2)

print('-------PyTorch------\n\n',t_tensor,'\n')
print('-------Numpy--------\n\n',n_array,'\n')

-------PyTorch------

 tensor([[0.0288, 0.2207],
        [0.8408, 0.1874]]) 

-------Numpy--------

 [[0.28240253 0.19429561]
 [0.13021437 0.49243112]] 



**4.DOT product between two torch tensor is done with the help of** -----> *torch.matmul(tensor A, tensar B)*

Note: any matrix multiplication(dot product) will comply only if matrix dimension follows the heuristic (X x M) and (M x Y)

In [46]:
#PyTorch
t_tensorA = torch.tensor([[2,3,4],[3,2,1]])
t_tensorB = torch.tensor([[1,2],[8,1],[2,5]])

#Numpy
n_arrayA = np.array([[2,3,4],[3,2,1]])
n_arrayB = np.array([[1,2],[8,1],[2,5]])

print('-------PyTorch------\n\n',torch.matmul(t_tensorA, t_tensorB),'\n')
print('-------Numpy--------\n\n',np.dot(n_arrayA, n_arrayB),'\n')

-------PyTorch------

 tensor([[34, 27],
        [21, 13]]) 

-------Numpy--------

 [[34 27]
 [21 13]] 



**5.Element Wise Multiplication between two torch tensor is done with the help of** -----> * tensor A * tensar B 

Note: This operation complies only if matrix dimension follows the heuristic (N x M) and (N x M) 

In [49]:
#PyTorch
t_tensorA = torch.tensor([[2,3,4],[3,2,1]])
t_tensorB = torch.tensor([[1,2,8],[2,5,1]])

#Numpy
n_arrayA = np.array([[2,3,4],[3,2,1]])
n_arrayB = np.array([[1,2,8],[2,5,1]])

print('-------PyTorch------\n\n',t_tensorA * t_tensorB,'\n')
print('-------Numpy--------\n\n',np.multiply(n_arrayA, n_arrayB),'\n')

-------PyTorch------

 tensor([[ 2,  6, 32],
        [ 6, 10,  1]]) 

-------Numpy--------

 [[ 2  6 32]
 [ 6 10  1]] 



**5. Zeros, Ones and Idenity Torch tensor can be created using** * ---> torch.zeros(a, b); torch.ones(a, b); torch.eyes(a, b); repectively*

In [61]:
#PyTorch
t_tensorA = torch.zeros(2,2)
t_tensorB = torch.ones(2,2)
t_tensorC = torch.eye(2,2)

#Numpy
n_arrayA = np.zeros([2,2])
n_arrayB = np.ones([2,2])
n_arrayC = np.identity(2)

print('-------PyTorch------\n\n',t_tensorA,'\n',t_tensorB, '\n', t_tensorC),
print('-------Numpy--------\n\n',n_arrayA,'\n', n_arrayB,'\n', n_arrayC)

-------PyTorch------

 tensor([[0., 0.],
        [0., 0.]]) 
 tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[1., 0.],
        [0., 1.]])
-------Numpy--------

 [[0. 0.]
 [0. 0.]] 
 [[1. 1.]
 [1. 1.]] 
 [[1. 0.]
 [0. 1.]]


**6.Convert numpy to torch tensor using** ---> * torch.from_numpy(numpy_array)*

**Convert troch to numpy using** ---> * torch_tensor.numpy()*

In [69]:
#PyTorch
t_tensor = torch.rand(2,2)

#Numpy
n_array = np.random.rand(2,2)

print('-------Numpy array to PyTorch------\n\n',torch.from_numpy(n_array))
print('-------Torch to Numpy array--------\n\n',t_tensorA.numpy())

-------Numpy array to PyTorch------

 tensor([[0.4202, 0.7448],
        [0.6882, 0.4216]], dtype=torch.float64)
-------Torch to Numpy array--------

 [[0. 0.]
 [0. 0.]]
